# Generated by Django 3.0.3 on 2020-07-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mbtiResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.IntegerField(max_length=255)),
            ],
        ),
    ]
