# Generated by Django 3.0.3 on 2020-07-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtiresult',
            name='password',
        ),
        migrations.AddField(
            model_name='mbtiresult',
            name='extraScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mbtiresult',
            name='feelScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mbtiresult',
            name='introScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mbtiresult',
            name='intuiScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mbtiresult',
            name='judgeScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mbtiresult',
            name='perceiScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mbtiresult',
            name='senseScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mbtiresult',
            name='thinkScore',
            field=models.IntegerField(default=0),
        ),
    ]
