# Generated by Django 3.0.3 on 2020-07-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0003_answerlist_inputclient_questionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputclient',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
