# Generated by Django 3.0.3 on 2020-07-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0004_inputclient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtiresult',
            name='gender',
        ),
        migrations.AddField(
            model_name='mbtiresult',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mbtiresult',
            name='password',
            field=models.IntegerField(default=0),
        ),
    ]
