# Generated by Django 3.0.3 on 2020-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0005_auto_20200722_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputclient',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inputclient',
            name='password',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='mbtiresult',
            name='password',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
