# Generated by Django 3.0.3 on 2020-07-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0005_auto_20200722_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerList',
        ),
    ]
