# Generated by Django 3.0.3 on 2020-07-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0009_auto_20200723_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtiresult',
            name='owner',
        ),
    ]
