# Generated by Django 3.0.3 on 2020-07-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0009_auto_20200724_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionList',
        ),
    ]
